spring.application.name=cadastro
#--- Postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=joabe
spring.datasource.password=CODEmaster88@
#--- Optional
spring.jpa.show-sql=true
#--- To prevent conflicts with fly_way
spring.jpa.hibernate.ddl-auto=none
